### PR TITLE
Merge of boston docs

### PR DESCRIPTION
**Pull request by steakunderscore**

### CODE REVIEW

**Comment by steakunderscore** [comment]
This PR is not the most useful in githubs interface. It might be better to view it as the following:
```bash
git remote add boston git@github.com:railsbridge/docs.git
git fetch --all
git diff origin/merge-of-boston-docs boston/master
```

**Comment by steakunderscore** [comment]
TODO:
 - [ ] Remove `respond_to` blocks from controller code examples

**Comment by mdeloupy** [comment]
@steakunderscore Looks good ! However I have 2 questions on the `Before the workshop` page : 

- [this section](https://github.com/railsbridge-montreal/docs/blob/e4629f0b1954581c0061013da631ecb1a87ea55f/sites/en/before-the-workshop/before-the-workshop.step#L10-L15) is titled `Students of the advanced class`, should we keep it even though there won't be any advanced students ?
- [the OSX section](https://github.com/railsbridge-montreal/docs/blob/e4629f0b1954581c0061013da631ecb1a87ea55f/sites/en/before-the-workshop/before-the-workshop.step#L19) might be a little outdated, the most recent version being `10.11` as stated [everywhere else](https://github.com/railsbridge-montreal/docs/blob/e4629f0b1954581c0061013da631ecb1a87ea55f/sites/en/installfest/macintosh.step#L7). Could you update that ?

**Comment by steakunderscore** [comment]
Thanks @mdeloupy. For the advanced section. I'm happy to leave it in. But I'll update the references to osx versions. I might actually clean up that whole file also.

**Comment by steakunderscore** [comment]
I still need to get the Vagrant VM image working before i can update the links to this.

**Pull request merged**
